package bubble

import "github.com/bubblenet/bubble/common"

var (
	ErrBubbleNotExist           = common.NewBizError(322001, "The bubble is not exist")
	ErrSenderIsNotCreator       = common.NewBizError(322002, "transaction sender must be the bubble creator")
	ErrBubbleUnableRelease      = common.NewBizError(322003, "The bubble is unable to release")
	ErrOperatorL1IsInsufficient = common.NewBizError(322004, "The operator of layer 1 is insufficient")
	ErrOperatorL2IsInsufficient = common.NewBizError(322005, "The operator of layer 2 is insufficient")
	ErrMicroNodeIsInsufficient  = common.NewBizError(322006, "The micro node is insufficient")
	ErrCodeException            = common.NewBizError(322007, "The contract code is empty or abnormal")
	ErrAccountNoEnough          = common.NewBizError(330000, "The account balance is insufficient")
	ErrStakingAccount           = common.NewBizError(330001, "The sender of the pledged token transaction is not the person of the pledged account")
	ErrERC20NoExist             = common.NewBizError(330002, "erc20 contract address does not exist")
	ErrEVMOrContractEmpty       = common.NewBizError(330003, "Evm or Contract is nil")
	ErrNoExecutableVM           = common.NewBizError(330004, "there is no executable EVM or WASM interpreter")
	ErrCannotSettled            = common.NewBizError(330005, "the bubble has been released and cannot be settled")
	ErrIsNotSubChainOpAddr      = common.NewBizError(330006, "the transaction sender is not the main chain operator address")
	ErrSettleAccListIncLength   = common.NewBizError(330007, "the length of the address participating in the settlement is incorrect")
	ErrSettleAccNoExist         = common.NewBizError(330008, "settlement account does not exist in the bubble")
	ErrStoreAccAssetToBub       = common.NewBizError(330009, "failed to Store the latest information about the staking assets of the account into bubble")
	ErrStoreL2HashToL1Hash      = common.NewBizError(330010, "failed to store sub-chain settlement transaction hash to main-chain settlement transaction hash")
	ErrGetL1HashByL2Hash        = common.NewBizError(330011, "failed to get main-chain settlement transaction hash to sub-chain settlement transaction hash")
	ErrBubbleIsNotRelease       = common.NewBizError(330012, "bubble cannot redeem the token until it is released")
	ErrEncodeTransferData       = common.NewBizError(330013, "Failed to generate data for ERC20 transfer interface")
	ErrEVMExecERC20             = common.NewBizError(330014, "evm fails to execute erc20 contract transfer interface")
	ErrStoreAccAsset            = common.NewBizError(330015, "failure to save account asset information to the specified bubble")
	ErrBubbleIsRelease          = common.NewBizError(330016, "bubble has released, Can not StakingToken token to the bubble")
	ErrGetTxHashListByBub       = common.NewBizError(330017, "failed to get bubble's transaction hash list")
)
